---
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.64.1/hugo_0.64.1_Linux-64bit.deb
  - sudo dpkg -i hugo_0.64.1_Linux-64bit.deb

script:
  - hugo

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $HCC_TOKEN
    keep_history: true
    local_dir: public
    repo: UICHCC/uichcc.github.io
    on:
      branch: master